### PR TITLE
Allow use of hammer config as defaults

### PR DESCRIPTION
**Pull request by jcpunk**
Reads in the hammer cli config to setup default values for user/pass/host.  Should be fully backwards compatible and fail gracefully if the config is not setup.

### CODE REVIEW

**Comment by evgeni** [comment]
that's a cool idea!

two things:
- there is also a hammer cli config in /etc/hammer/cli.modules.d/foreman.yml - should we read that one too?
- I'd prefer if the password would not be echoed when I run --help, hell knows who looks on my screen :)

**Comment by jcpunk** [comment]
My tests show with metavar defined, --help doesn't echo defaults to the screen.

I've added parsing of the /etc/ file as well.

**Comment by evgeni** [comment]
Right, sorry. It only shows the value when you have %(default)s in the help string, which we do not.
LGTM then

will test sometime this week if @sideangleside is not quicker :)

**Comment by jcpunk** [comment]
:) if this works out, it is probably worth adding the behavior to the other tools.  Alas, I'm not a ruby programmer....

**Comment by sideangleside** [comment]
- You'd probably want an error message/notification in the event you cannot import the yaml module. Since the yaml module isn't a default module (at least on EL7), you may want to tell the user to install it. Doesn't have to be anything crazy. Something like

```
except ImportError:
    print 'Could not import YAML module to parse hammer configuration file. verify that it is installed properly'
    print 'Defaulting to prompting for username/password'
    pass
```
- Also, you'd want to update `print _hammer_config[':foreman'][':host'].split('/')[1]` to be `print _hammer_config[':foreman'][':host'].split('/')[2]`

```
>>> host = 'https://satellite.example.com'
>>> host.split('/')
['https:', '', 'satellite.example.com']
```

Otherwise, your PR LGTM

**Comment by jcpunk** [comment]
Changes made

**Comment by sideangleside** [comment]
Merged. Thanks @jcpunk

**Pull request merged**
