### PR TITLE
add a column indicating whether we have an derived sub

### PR DESCRIPTION
**Pull request by evgeni**
useful to distinguish VDC subs

### CODE REVIEW

**Comment by sideangleside** [comment]
There are subscription types that support > 1 guest that aren't unlimited. (commonly 4, 8 or 25 guests). Not common, but common _enough_

**Comment by evgeni** [comment]
Will those also end up with "quantity = -1" in the API? Basically I don't care how we name the column, the data I want is: this sub was free of further charge, don't care where it came from :)

**Comment by sideangleside** [comment]
I dont know for sure if they will end up with "quantity =-1". In fact I doubt it. It might be better to view the 'type' field, which should list a subscription as:
-  **NORMAL** (for subs that the user paid for), and 
- **ENTITLEMENT_DERIVED** (for derived subscriptions)

**Comment by evgeni** [comment]
There is no type in the response to `/katello/api/v2/systems/:id/subscriptions/`. That would be too easy.

**Comment by sideangleside** [comment]
Oh great. Something only in 6.2, I gather. from`/api/hosts/:id/subscriptions/`

```
{

    "total": 1,
    "subtotal": 1,
    "page": 1,
    "per_page": 1,
    "error": null,
    "search": null,
    "sort": {
        "by": null,
        "order": null
    },
    "results": [
        {
            "quantity_consumed": 1,
            "id": 212,
            "cp_id": "2c918093561eaa3901563101613820e4",
            "subscription_id": 141,
            "name": "Red Hat Enterprise Linux Server, Premium (1-2 sockets) (Unlimited guests) with Smart Management",
            "start_date": "2016-07-04T04:00:00.000+0000",
            "end_date": "2017-07-04T03:59:59.000+0000",
            "available": -4,
            "quantity": -1,
            "consumed": 3,
            "account_number": 1111111,
            "contract_number": 1222222,
            "support_level": "Premium",
            "product_id": "RH0149450",
            "sockets": 2,
            "cores": null,
            "ram": null,
            "instance_multiplier": 1,
            "stacking_id": null,
            "multi_entitlement": null,
            "type": "ENTITLEMENT_DERIVED",
            "product_name": "Red Hat Enterprise Linux Server, Premium (1-2 sockets) (Unlimited guests) with Smart Management",
            "unmapped_guest": false,
            "virt_only": true,
            "host": {
                "id": "9a73406a-498f-4178-908b-3ac8fcaee884",
                "name": "kvm01.example.com"
            }
        }
    ]

}

```

**Comment by evgeni** [comment]
Heh. Frack.

**Comment by evgeni** [comment]
@sideangleside OK, so I made this a 6.2+ feature now, using the proper keywords etc.
also renamed the field to "derived entitlement"

see also https://github.com/candlepin/candlepin/blob/master/server/src/main/java/org/candlepin/model/Pool.java#L166-L175

**Review by sideangleside — APPROVED** [review]
Looks good to me. Though you are gonna probably need to rebase on latest master since I merged #25

**Comment by evgeni** [comment]
Rebased.

**Pull request merged**
