### PR TITLE
add Virtual Guest Count to the report

### PR DESCRIPTION
**Pull request by evgeni**
this adds a new column (num_virtual_guests) which will contain the
number of guests the hypervisor has, if any.

currently not enabled by default in any report

Fixes: #23

### CODE REVIEW

**Comment by sideangleside** [comment]
I am not seeing the new column in the report (see [this report](https://docs.google.com/spreadsheets/d/1PMoK-MuCBLxc4MdeCgDG2uswDH0IGTIgXudi67EXxH4/edit#gid=1622577008)) . Running with `--verbose` I definitely see the `num_virtual_guests` field with the proper output. I suspect it just isnt getting written into the report. (I am using the _original_ report format)

**Comment by evgeni** [comment]
Correct, I did not add it to any reports. Yet.

You can do `-c hostname,num_virtual_guests` to select the proper columns.

**Comment by sideangleside** [comment]
I'd add it to all the reports. it is a useful enough field that I'd want it by default.

**Comment by evgeni** [comment]
Added to "original" and "spacewalk-report-inventory-customized" formats, not touching "spacewalk-report-inventory" to remain compat with spacewalk-report

**Review by sideangleside — APPROVED** [review]
👍

**Pull request merged**
